name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
  workflow_call:
    secrets:
      username:
          description: 'Registry username'
          required: true
      password:
        description: 'Registry password'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: |
            ${{ secrets.username }}/my-image:latest
            ${{ secrets.username }}/my-image:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.username }}/my-image:latest
            ${{ secrets.username }}/my-image:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max