name: Sync Files and Auto Approve PRs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      pr_urls: ${{ steps.sync.outputs.pr_urls }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run GitHub File Sync
        id: sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          # SKIP_PR: true
      - name: Set PR URLs Output
        run: |
          echo "pr_urls=${{ steps.sync.outputs.pull_request_urls }}" >> $GITHUB_OUTPUT

  approve-pr:
    runs-on: ubuntu-latest
    needs: sync
    environment: workflow_sync
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Approve PRs
        run: |
          for url in $(echo $PR_URLS | jq -r '.[]'); do
            REPO_NAME=$(echo $url | awk -F'/' '{print $(NF-3)"/"$(NF-2)}') # Extract OWNER/REPO
            PR_NUMBER=$(echo $url | awk -F'/' '{print $NF}') # Extract PR number
            echo "Approving PR #$PR_NUMBER in repository $REPO_NAME"
            
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d '{"event": "APPROVE"}' \
                 "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER/reviews"
          done

