name: Sync Files and Auto Approve PRs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      pr_urls: ${{ steps.sync.outputs.pr_urls }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run GitHub File Sync
        id: sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          # SKIP_PR: true
      - name: Set PR URLs Output
        run: |
          echo "pr_urls=${{ steps.sync.outputs.pull_request_urls }}" >> $GITHUB_OUTPUT

  approve-pr:
    runs-on: ubuntu-latest
    needs: sync
    environment: workflow_sync
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Approve PRs
        run: |
          echo "Approving PRs..."
          for pr_url in ${{ needs.sync.outputs.pr_urls }}; do
            pr_number=$(basename "$pr_url")
            api_url="https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/reviews"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"event": "APPROVE"}' "$api_url"
            echo "Approved PR #$pr_number"
          done
