name: Automatic Workflows Sync

on:
  push:
    branches:
    - main
  workflow_dispatch:


permissions:
  pull-requests: write
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      pr_urls: ${{ steps.set-pr-urls.outputs.pr_urls }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run GitHub File Sync
      id: sync
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Set PR URLs Output
      id: set-pr-urls
      run: echo "pr_urls=$(echo '${{ steps.sync.outputs.pull_request_urls }}' | jq -c .)" >> $GITHUB_OUTPUT

  approve-and-merge:
    runs-on: ubuntu-latest
    needs: sync
    if: ${{ needs.sync.outputs.pr_urls != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        pr_url: ${{ fromJson(needs.sync.outputs.pr_urls) }}
    environment:
      name: workflow_sync
      url: ${{ matrix.pr_url }}
    steps:

    - name: Generate GitHub App Token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Configure GitHub CLI
      run: |
        echo "::group::Install GitHub CLI"

        wget https://github.com/cli/cli/releases/download/v2.66.1/gh_2.66.1_linux_amd64.deb
        sudo dpkg -i gh_2.66.1_linux_amd64.deb

        echo "::endgroup::"

        echo "::group::Configure GitHub CLI"

        unset GH_TOKEN
        git config --global credential.helper store
        # Comment out for GHE Server
        gh config set git_protocol https
        gh auth login --with-token <<< "${{ steps.generate-token.outputs.token }}"
        # Uncomment for GHE Server
        # echo "https://x-access-token:${GH_TOKEN}@${GITHUB_SERVER_URL#https://}" > ~/.git-credentials
        # gh config set git_protocol https
        # gh auth login --with-token --hostname ${GITHUB_SERVER_URL#https://} <<< "${GH_TOKEN}"

        echo "::endgroup::"

    - name: List Token Permissions
      run: |
        gh api \
          -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /user

    - name: Approve the Pull Request
      run: |
        gh pr review ${{ matrix.pr_url }} --approve

    - name: Merge the Pull Request
      run: |
        gh pr merge ${{ matrix.pr_url }} --merge
