name: Sync Files and Auto Approve PRs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      pr_urls: ${{ steps.set-pr-urls.outputs.pr_urls }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run GitHub File Sync
        id: sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Set PR URLs Output
        id: set-pr-urls
        run: echo "pr_urls=${{ steps.sync.outputs.pull_request_urls }}" >> $GITHUB_OUTPUT

  approve-pr:
    runs-on: ubuntu-latest
    needs: sync
    environment: workflow_sync
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug PR URLs
        run: echo "Raw PR_URLS: \"${{ needs.sync.outputs.pr_urls }}\""

      - name: Approve PRs
        run: |
          PR_URL
