name: Sync Files and Auto Approve PRs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      pr_urls: ${{ steps.set-pr-urls.outputs.pr_urls }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run GitHub File Sync
        id: sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Set PR URLs Output
        id: set-pr-urls
        run: echo "pr_urls=${{ steps.sync.outputs.pull_request_urls }}" >> $GITHUB_OUTPUT

  approve-pr:
    runs-on: ubuntu-latest
    needs: sync
    environment: workflow_sync
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Approve PRs
        run: |
          PR_URLS_JSON="${{ needs.sync.outputs.pr_urls }}"
          echo "Processing PRs from: $PR_URLS_JSON"

          # Convert PR_URLS_JSON to a bash array
          PR_URLS=($(echo "$PR_URLS_JSON" | jq -r '.[]'))
          for url in "${PR_URLS[@]}"; do
            echo "Processing URL: $url"
            # Extract OWNER/REPO from URL
            REPO_NAME=$(echo "$url" | sed -E 's#https://github.com/([^/]+/[^/]+)/pull/[0-9]+#\1#')
            PR_NUMBER=$(echo "$url" | sed -E 's#.*/pull/([0-9]+)#\1#')
            if [[ -z "$REPO_NAME" || -z "$PR_NUMBER" ]]; then
              echo "Skipping invalid URL: $url"
              continue
            fi
            echo "Approving PR #$PR_NUMBER in repository $REPO_NAME"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d '{"event": "APPROVE"}' \
                 "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER/reviews"
          done
